vibration
MahmoudMabrok/Azkary pull request #3
Opened 2020-10-08 16:51 UTC by hamza94max

2020-10-08 17:48 UTC, MahmoudMabrok requested changes
see comments

2020-10-08 17:48 UTC, MahmoudMabrok commented on app/src/main/java/com/mahmoudmabrok/azakri/feature/display/DisplayAzkar.java
> +                Vibrator v = (Vibrator) getSystemService(Context.VIBRATOR_SERVICE);
we want to add vibrate after each finish to zeker not all zeker

2020-10-08 17:48 UTC, MahmoudMabrok commented on app/src/main/java/com/mahmoudmabrok/azakri/feature/display/DisplayAzkar.java
> +                Vibrator v = (Vibrator) getSystemService(Context.VIBRATOR_SERVICE);
also try to add it as HELPER CLASS so it can be used in other places

2020-10-09 15:35 UTC, hamza94max commented on app/src/main/java/com/mahmoudmabrok/azakri/feature/display/DisplayAzkar.java
> +                Vibrator v = (Vibrator) getSystemService(Context.VIBRATOR_SERVICE);
Done @MahmoudMabrok

2020-10-10 20:16 UTC, MahmoudMabrok approved these changes

2020-10-10 20:16 UTC, merged